server:
  port: ${PORT:0}
spring:
  application:
    name: transaction
  feign:
    client:
      config:
        default:
          connectTimeout: 5000 #tempo maximo de se conectar com a api externa
          readTimeout: 300  #tempo de r4esposta da api
          loggerLevel: FULL
          retryer:
            period: 100  #retentativa caso o sistema externo fique fora
            maxPeriod: 1000 #tempo maximo de retentativa
            maxAttempts: 3 #quantidade de vezes para tentar antes de falhar

